import random

word_list = list([
    'conscious', 'concession', 'qualified', 'democratic', 'accountant', 'advantage', 'reinforce', 'disappoint', 'permission', 'mainstream', 'concentrate', 'character', 'spontaneous', 'embarrassment', 'machinery', 'transparent', 'dimension', 'manufacturer', 'withdrawal', 'respectable', 'settlement', 'orchestra', 'gregarious', 'circumstance', 'entitlement', 'disappear', 'superintendent', 'principle', 'direction', 'separation', 'hypothesize', 'distributor', 'memorandum', 'contemporary', 'quotation', 'preparation', 'strikebreaker', 'color-blind', 'anticipation', 'first-hand', 'establish', 'recession', 'demonstration', 'homosexual', 'federation', 'simplicity', 'illustrate', 'threshold', 'beautiful', 'celebration', 'allowance', 'acceptance', 'brilliance', 'population', 'prescription', 'highlight', 'restoration', 'foundation', 'exclusive', 'confidence', 'unfortunate', 'undermine', 'possession', 'identification', 'proportion', 'credibility', 'firefighter', 'eavesdrop', 'demonstrator', 'literature', 'beneficiary', 'incredible', 'motivation', 'prosecute', 'catalogue', 'systematic', 'technology', 'mathematics', 'exhibition', 'straighten', 'expenditure', 'circumstance', 'demonstration', 'fabricate', 'leadership', 'ambiguity', 'instrument', 'unanimous', 'convulsion', 'speculate', 'vegetarian', 'suffering', 'consumption', 'executrix', 'guideline', 'commitment', 'exploration', 
    'available', 'basketball', 'dismissal', 'allowance', 'acceptance', 'brilliance', 'population', 'prescription', 'highlight', 'restoration', 'foundation', 'exclusive', 'confidence', 'unfortunate', 'undermine', 'possession', 'identification', 'proportion', 'credibility', 'firefighter', 'eavesdrop', 'demonstrator', 'literature', 'beneficiary', 'incredible', 'motivation', 'prosecute', 'catalogue', 'systematic', 'technology', 'mathematics', 'exhibition', 'straighten', 'expenditure', 'circumstance', 'demonstration', 'fabricate', 'leadership', 'ambiguity', 'instrument', 'unanimous', 'convulsion', 'speculate', 'vegetarian', 'suffering', 'consumption', 'executrix', 'guideline', 'commitment', 'exploration', 'available', 'basketball', 'dismissal', 'brilliance', 'dimension', 'conglomerate', 'repetition', 'opposition', 'elaborate', 'credibility', 'appointment', 'censorship', 'discriminate', 'integrated', 'detective', 'publisher', 'motivation', 'transport', 'secretary', 'education', 'continental', 'appreciate', 'chemistry', 'competition', 'communication', 'comfortable', 'staircase', 'advertising', 'influence', 'plagiarize', 'conception', 'shareholder', 'prediction', 'recommend', 'demonstrate', 'performer', 
    'confusion', 'sculpture', 'protection', 'interrupt', 'franchise', 'miscarriage', 'disturbance', 'acceptance', 'discipline', 'constraint', 'acquisition', 'correction', 'variation', 'cathedral', 'prosecute', 'legislature', 'disappear', 'redundancy', 'photography', 'preoccupation', 'nomination', 'interactive', 'confrontation', 'attachment', 'nationalist', 'exception', 'constraint', 'protection', 'contribution', 'neighborhood', 'guerrilla', 'deprivation', 'diplomatic', 'nightmare', 'absorption', 'execution', 'reinforce', 'microphone', 'conviction', 'tradition', 'restoration', 'copyright', 'institution', 'machinery', 'classroom', 'improvement', 'explosion', 'inflation', 'favourite', 'girlfriend', 'introduce', 'leadership', 'inspector', 'reproduction', 'treasurer', 'cigarette', 'reservoir', 'sympathetic', 'discourage', 'possession', 'conception', 'vegetable', 'motivation', 'reduction', 'infection', 'privilege', 'constitution'
    ])

words = str(word_list)

num_of_words = int(words.count("'") / 2) - 1

rand_word = word_list[random.randrange(0, num_of_words)]
rand_word = str(rand_word)

if __name__ == '__main__':
    print(num_of_words + 1)
    print(rand_word)